/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/* Controle de jogadores e fichas de poker, na modalidade cash game. */
/*              Desenvolvido por: Reinaldo Silveira                  */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

CREATE DATABASE IF NOT EXISTS db_poker CHARACTER SET utf8 COLLATE utf8_general_ci;
USE db_poker;

CREATE TABLE TCAIXA (
    CAIXA_ID          INT NOT NULL AUTO_INCREMENT,
    TICKET_ID         INT NOT NULL,
    VR_DEB            NUMERIC(15,2) DEFAULT 0 NOT NULL,
    VR_CRED           NUMERIC(15,2) DEFAULT 0 NOT NULL,
    VR_CALCULADO      NUMERIC(15,2) DEFAULT 0 NOT NULL,
    VR_ACERTO         NUMERIC(15,2) DEFAULT 0 NOT NULL,
    VR_TROCO          NUMERIC(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TCAIXA PRIMARY KEY (CAIXA_ID)
) ENGINE=InnoDB;

CREATE TABLE TFICHAS (
    FICHA_ID  INT NOT NULL AUTO_INCREMENT,
    NOME      VARCHAR(30),
    COR       VARCHAR(20),
    VALOR     NUMERIC(15,2) DEFAULT 0,
    CONSTRAINT PK_TFICHAS PRIMARY KEY (FICHA_ID)
) ENGINE=InnoDB;

CREATE TABLE TJOGADORES (
    JOGADOR_ID  INT NOT NULL AUTO_INCREMENT,
    NOME        VARCHAR(60),
    BLOQUEADO   BIT DEFAULT 0 NOT NULL,
    DT_INC      DATETIME,
    EMAIL       VARCHAR(100),
    CONSTRAINT PK_TJOGADORES PRIMARY KEY (JOGADOR_ID)
) ENGINE=InnoDB;

CREATE TABLE TJOGOS (
    JOGO_ID     INT NOT NULL AUTO_INCREMENT,
    DT_JOGO     DATE,
    LOCAL_ID    INT NOT NULL,
    OBS         VARCHAR(200),
    FINALIZADO  BIT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TJOGOS PRIMARY KEY (JOGO_ID)
) ENGINE=InnoDB;

CREATE TABLE TLOCAIS (
    LOCAL_ID   INT NOT NULL AUTO_INCREMENT,
    DSC_LOCAL  VARCHAR(60),
    CONSTRAINT PK_TLOCAIS PRIMARY KEY (LOCAL_ID)
) ENGINE=InnoDB;

CREATE TABLE TTICKETS (
    TICKET_ID   INT NOT NULL AUTO_INCREMENT,
    BAIXADO     BIT DEFAULT 0 NOT NULL,
    JOGO_ID     INT NOT NULL,
    JOGADOR_ID  INT NOT NULL,
    CONSTRAINT PK_TTICKETS PRIMARY KEY (TICKET_ID),
    CONSTRAINT UK_TTICKETS UNIQUE (JOGO_ID, JOGADOR_ID)
) ENGINE=InnoDB;

CREATE TABLE TTICKETSLAN (
    TICKETLAN_ID  INT NOT NULL AUTO_INCREMENT,
    TICKET_ID     INT NOT NULL,
    TIPOLAN       CHAR(1),
    FICHA_ID      INT,
    QTD_FICHAS    INT,
    VAL_FICHA     NUMERIC(15,2),
    VAL_APURADO   NUMERIC(15,2),
    DT_INC        DATETIME,
    DT_ALT        DATETIME,
    CONSTRAINT PK_TTICKETSLAN PRIMARY KEY (TICKETLAN_ID)
) ENGINE=InnoDB;

CREATE TABLE TUSUARIOS (
    USR_ID     INT NOT NULL AUTO_INCREMENT,
    USR_NOME   VARCHAR(60),
    USR_LOGIN  VARCHAR(20),
    USR_SENHA  VARCHAR(200),
    BLOQUEADO  BIT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TUSUARIOS PRIMARY KEY (USR_ID)
) ENGINE=InnoDB;


ALTER TABLE TCAIXA ADD CONSTRAINT FK_TCAIXA_TTICKETS FOREIGN KEY (TICKET_ID) REFERENCES TTICKETS (TICKET_ID);
ALTER TABLE TJOGOS ADD CONSTRAINT FK_TJOGOS_TLOCAIS FOREIGN KEY (LOCAL_ID) REFERENCES TLOCAIS (LOCAL_ID);
ALTER TABLE TTICKETS ADD CONSTRAINT FK_TTICKETS_TJOGOS FOREIGN KEY (JOGO_ID) REFERENCES TJOGOS (JOGO_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TTICKETS ADD CONSTRAINT FK_TTICKETS_TJOGADORES FOREIGN KEY (JOGADOR_ID) REFERENCES TJOGADORES (JOGADOR_ID);
ALTER TABLE TTICKETSLAN ADD CONSTRAINT FK_TTICKETSLAN_TFICHAS FOREIGN KEY (FICHA_ID) REFERENCES TFICHAS (FICHA_ID);
ALTER TABLE TTICKETSLAN ADD CONSTRAINT FK_TTICKETSLAN_TTICKETS FOREIGN KEY (TICKET_ID) REFERENCES TTICKETS (TICKET_ID) ON DELETE CASCADE ON UPDATE CASCADE;


INSERT INTO TUSUARIOS(USR_NOME, USR_LOGIN, USR_SENHA) VALUES('Administrador', 'admin', MD5('admin'));

INSERT INTO TFICHAS(NOME, COR) VALUES('Preta', '#000000');
INSERT INTO TFICHAS(NOME, COR) VALUES('Azul', '#0000ff');
INSERT INTO TFICHAS(NOME, COR) VALUES('Vermelha', '#ff0000');
INSERT INTO TFICHAS(NOME, COR) VALUES('Verde', '#008000');
INSERT INTO TFICHAS(NOME, COR) VALUES('Branca', '#ffffff');
